joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 330
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 330
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 150
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 300.0
    has_effort_limits: true
    max_effort: 56
